### PR TITLE
Ability to change chart type

### PR DESCRIPTION
**Pull request by redet-G**

### CODE REVIEW

**Comment by redet-G** [comment]
@RihanaE Can you please test and merge this?

**Comment by RihanaE** [comment]
Okay, I will

**Comment by RihanaE** [comment]
It successfully changes the chart type for those that support it, but while changing for some of dashboard items, the chart will be hidden or the legend will overlap with the chart. 


￼￼

**Comment by redet-G** [comment]
Can you be more specific?
Something like, when this chart is changed to this chart type it does this.

**Comment by redet-G** [comment]
Let's create a new issue and merge this for now

**Comment by RihanaE** [comment]
For example like on test4 ScatterChart is changed to pie chart and on test Bar chart converted to piechart

**Comment by RihanaE** [comment]
Okay

**Pull request merged**
