### PR TITLE
Add support for area chart type

### PR DESCRIPTION
**Pull request by RihanaE**

### CODE REVIEW

**Comment by redet-G** [comment]
This is great, But, we need to stick to the x-charts library of mui for the time being.

**Comment by RihanaE** [comment]
Okay

**Comment by redet-G** [comment]
I can take on this task if you are not interested in working on it.

**Comment by RihanaE** [comment]
I am interested in working on it. However, I was wondering if we could minimize the code inside DashboardItem.js by creating different components for each chart type.

**Pull request closed without merging**
