### PR TITLE
shareable link for each dashboard items

### PR DESCRIPTION
**Pull request by RihanaE**

### CODE REVIEW

**Comment by RihanaE** [comment]
On dashboard 'test2', there are items with an 'undefined' id, which result in being unable to access them. What do we do?

**Comment by redet-G** [comment]
If I remember correctly we have modified the code so that it uses `_id` property of the dashboard item in such cases.

**Comment by redet-G** [comment]
Additionally, you are still on the #5-adding_support_for_area_chart_type" branch. I am seeing a conflict on `chart.js` file. It is always advised to create a new feature branch for each of the pull requests and stay in sync with the main branch.

**Comment by RihanaE** [comment]
Okay, will do that in the future.

**Pull request merged**
