### PR TITLE
Feature/timeline map view

### PR DESCRIPTION
**Pull request by RihanaE**

### CODE REVIEW

**Comment by redet-G** [comment]
@RihanaE Created a testing timeline map view on `map test` dashboard and a chart named `Map org unit layer test` You can test your implementation there. 

https://deploy-preview-79--public-dashboard.netlify.app/?dashboard=f0fwbBqCy3r

**Comment by RihanaE** [comment]
the color not being displayed is fixed

**Comment by redet-G** [comment]
This is great. 

But we are still missing the label for the slider
image
image

**Comment by RihanaE** [comment]
I am unable to access the map-related dashboards that I can edit.

**Comment by redet-G** [comment]
try now

**Comment by RihanaE** [comment]
It works. Thanks

**Comment by RihanaE** [comment]
label for the slider is fixed

**Comment by redet-G** [comment]
The label is not being displayed correctly. 
Currently displaying this
image
While it should have done to display this
image

You can reproduce it using the following chart
?dashboard=f0fwbBqCy3r&dashboardItemId=y7xqxl370E7

**Comment by redet-G** [comment]
I'm seeing a merge conflict can you please resolve it while you are at it?

**Comment by RihanaE** [comment]
Screenshot 2024-10-25 at 13 46 11

Shouldn't it display the years retrieved from the fetched data like the one in the above?

**Comment by redet-G** [comment]
The month is repeated twice.

**Comment by RihanaE** [comment]
The branch conflict is resolved

**Pull request closed without merging**
